version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306" 
    environment:
      MARIADB_ROOT_PASSWORD: 12345678
      MARIADB_DATABASE: beer 
      MARIADB_USER: sharp                  
      MARIADB_PASSWORD: 12345678 
    volumes:
      - db_data:/var/lib/mysql 
    networks:
      - komgrip-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - komgrip-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_USERNAME: sharp
      MONGO_INITDB_PASSWORD: 111111
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - komgrip-network

volumes:
  db_data:
  mongo-data:
    driver: local
networks:
  komgrip-network:
    driver: bridge